name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs weekly on Sunday
  workflow_dispatch:  # Allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          base: humble
          head: humble